version: "3.9"
services:
  nginx:
    image: nginx
    volumes:
      - ./mirrulations-nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
  redis:
    image: redis
    volumes:
      - "~/data/redis:/data"
  mongo:
    image: mongo
    volumes:
      - "~/data/db:/data/db"
  work_generator:
    build:
      context: mirrulations-work-generator
    env_file: env_files/work_gen.env
  work_server:
    build:
      context: mirrulations-work-server
  dashboard:
    build:
      context: mirrulations-dashboard
  client1:
    build:
      context: mirrulations-client
    env_file: env_files/client1.env

