version: "3.9"
services:
  redis:
    image: redis
  work_server:
    build:
      context: .
      dockerfile: Dockerfile.work_server
    links:
      - redis
  client1:
    build:
      context: .
      dockerfile: Dockerfile.client
    env_file: env_files/client1.env
    links:
      - work_server

