version: "3.9"
services:
  nginx:
    image: nginx
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
  redis:
    image: redis
    volumes:
      - "~/data/redis:/data"
  work_server:
    build:
      context: src/c21server/work_server
  dashboard:
    build:
      context: src/c21server/dashboard
  client1:
    build:
      context: src/c21client
    env_file: env_files/client1.env

