version: "3.9"
services:
  redis:
    image: redis
    volumes:
      - "~/data/redis:/data"
  work_server:
    build:
      context: src/c21server/work_server
  dashboard:
    build:
      context: src/c21server/dashboard
    ports:
      - "5000:5000"
  client1:
    build:
      context: src/c21client
    env_file: env_files/client1.env

